// Mock property data for demo purposes (used when backend is unavailable)
export const mockProperties = [
    {
        _id: '1',
        title: 'Modern Luxury Apartment',
        description: 'A stunning modern apartment in the heart of the city with breathtaking skyline views. Features premium finishes, open-concept living, and state-of-the-art appliances.',
        price: 3500,
        city: 'New York',
        location: { latitude: 40.7128, longitude: -74.006 },
        propertyType: 'apartment',
        amenities: ['wifi', 'parking', 'security'],
        images: [{ url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80' }],
        ownerId: { name: 'James Wilson', email: 'james@example.com' },
        aiScore: 92,
        createdAt: new Date('2024-01-15'),
    },
    {
        _id: '2',
        title: 'Cozy Family House with Garden',
        description: 'Spacious family house with a beautifully landscaped garden, perfect for kids and pets. Located in a quiet, safe neighborhood near top-rated schools.',
        price: 2800,
        city: 'Los Angeles',
        location: { latitude: 34.0522, longitude: -118.2437 },
        propertyType: 'house',
        amenities: ['parking', 'garden', 'security'],
        images: [{ url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80' }],
        ownerId: { name: 'Sarah Ahmed', email: 'sarah@example.com' },
        aiScore: 88,
        createdAt: new Date('2024-01-20'),
    },
    {
        _id: '3',
        title: 'Minimalist Studio in Downtown',
        description: 'A beautifully designed minimalist studio ideal for young professionals. Walking distance to cafes, restaurants, and public transport hubs.',
        price: 1200,
        city: 'Chicago',
        location: { latitude: 41.8781, longitude: -87.6298 },
        propertyType: 'studio',
        amenities: ['wifi', 'security'],
        images: [{ url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80' }],
        ownerId: { name: 'Mike Chen', email: 'mike@example.com' },
        aiScore: 75,
        createdAt: new Date('2024-02-01'),
    },
    {
        _id: '4',
        title: 'Beachfront Villa with Pool',
        description: 'Exclusive beachfront property with a private pool, direct beach access, and panoramic ocean views. The ultimate luxury living experience.',
        price: 6500,
        city: 'Miami',
        location: { latitude: 25.7617, longitude: -80.1918 },
        propertyType: 'house',
        amenities: ['wifi', 'parking', 'pool', 'security'],
        images: [{ url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80' }],
        ownerId: { name: 'Elena Rivera', email: 'elena@example.com' },
        aiScore: 97,
        createdAt: new Date('2024-02-05'),
    },
    {
        _id: '5',
        title: 'Uptown Executive Apartment',
        description: 'Premium executive apartment in an upscale neighborhood. Features concierge services, gym access, rooftop lounge, and stunning city panoramas.',
        price: 4200,
        city: 'San Francisco',
        location: { latitude: 37.7749, longitude: -122.4194 },
        propertyType: 'apartment',
        amenities: ['wifi', 'parking', 'pool', 'security'],
        images: [{ url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80' }],
        ownerId: { name: 'David Park', email: 'david@example.com' },
        aiScore: 85,
        createdAt: new Date('2024-02-10'),
    },
    {
        _id: '6',
        title: 'Charming Countryside Home',
        description: 'A charming countryside retreat surrounded by nature, featuring exposed brick walls, wooden beams, and a large porch with scenic mountain views.',
        price: 1900,
        city: 'Denver',
        location: { latitude: 39.7392, longitude: -104.9903 },
        propertyType: 'house',
        amenities: ['parking', 'garden'],
        images: [{ url: 'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?ixlib=rb-4.0.3&auto=format&fit=crop&w=1470&q=80' }],
        ownerId: { name: 'Lisa Thompson', email: 'lisa@example.com' },
        aiScore: 70,
        createdAt: new Date('2024-02-15'),
    },
];
